### PR TITLE
New ui of dark contrast

### PR DESCRIPTION
**Pull request by Ashwani-Verma-07**
added some dark colors for better understanding
Screenshot (61)

### CODE REVIEW

**Comment by waldyrious** [comment]
Why not keep the header as blue as it currently is? I don't see how changing it to brown contributes to the dark mode style.

Furthermore, I'd recommend setting the timeline entry boxes (`.timeline-description`) to a dark background color (say, `#333333`) and a light text color (say, `#cccccc`). This should of course be accompanied by setting the arrows (`.timeline-description:after`) to the same background color, and the links to a lighter blue, perhaps reusing the same one used for the header, i.e. `#7ACBFF`. The result would look something like this:

Screenshot from 2021-11-28 13-36-16

WDYT?

**Comment by Ashwani-Verma-07** [comment]
ok sir can I do the same?
what you mentioned in comment.

**Comment by molly** [comment]
If you wanted to add a dark _mode_ I wouldn't object, but I would rather not entirely replace the current color scheme.

**Comment by Ashwani-Verma-07** [comment]
ok 
I am an undergrad student at akgec.
I want to contribute in wikimedia projects and want to contribute in html, css, javascript.
can you  give me  some projects or rather tell where to find?

**Comment by molly** [comment]
> ok I am an undergrad student at akgec. I want to contribute in wikimedia projects and want to contribute in html, css, javascript. can you give me some projects or rather tell where to find?

https://www.mediawiki.org/wiki/How_to_contribute

**Comment by waldyrious** [comment]
Hey @Ashwani-Verma-07, to make the styles apply to dark mode only, you need to add a new block at the end of `main.css` with

```css
@media (prefers-color-scheme: dark) {
  /* Dark-mode styles here */
}
```

...rather than directly editing the existing styles. See more details [here](https://css-tricks.com/dark-modes-with-css/).

Also, you seem to have edited the `index.html`, apparently by mistake? You might want to undo those changes.

**Comment by Ashwani-Verma-07** [comment]
yes it was done via mistake _index.html___

**Comment by Ashwani-Verma-07** [comment]
Screenshot (77)
done sir as directed by you

**Pull request merged**
