### PR TITLE
Note that Erik was also the DD

### PR DESCRIPTION
**Pull request by legoktm**
and and is a bit weird, but I couldn't think of better way at 1am.

### CODE REVIEW

**Comment by molly** [comment]
It is, but I'm with you—seems the best way to put it. Perhaps some wordsmith will come along and fix it for us :smile:

**Comment by legoktm** [comment]
I totally forgot until I read it just now that Erik was also a former board member. Do we want to include all of the hats he once wore (MediaWiki developer, VP of Engineering, etc.), or just the ones he was holding at the time?

**Comment by Thehelpfulone** [comment]
We haven't included hats that others wore (for example Philippe's had several hats), but maybe for Erik it would be worth it for historical context?

**Comment by molly** [comment]
We could add it, though I haven't generally been adding role changes unless they happened during the time after Lila became ED.

**Pull request merged**
